### ISSUE TITLE
app not running

### ISSUE THREAD

**Issue by seiyajin** [chianjin/realesrgan-gui#1]
seem app build python 3.10, tried to build from python 3.8 result success but still can not running the app, no script error found

**Comment by chianjin** [comment]
please run `realesrgan-ncnn-vulkan.exe` in `cmd` box, check it can run correctly.

**Comment by seiyajin** [comment]
thanks for reply my question, the problem is persist in RealESRGAN-GUI.exe, the app can't lauch, can you build frondend GUI support for older python 3.8 , and win7 support, thank

**Comment by chianjin** [comment]
There is a new version support Python3.8 and win7.
Try it and enjoy it.

**Comment by seiyajin** [comment]
thx for the update
